site_name: Kin Chong O/A Level Notes
site_url: https://wkc75.github.io/Wong_Kin_Chong_O-A_level_notes/

theme:
  name: material

extra_css:
  - stylesheets/definition-box.css

nav:
  - Home: index.md
  - A Level:
      - H2 Chemistry:
          - 1. Atomic Structure:
              - Chapter Overview: a-level/h2-chemistry/chap-one-atomic-structure/learning-outcome.md
              - 1.1 Atom and subatomic particles:
                  - 1.1.1 Atoms and Subatomic Particles: a-level/h2-chemistry/chap-one-atomic-structure/part1AtomAndSubatomicParticles/atom-and-subatomic-particles.md
                  - 1.1.2 Isotopes: a-level/h2-chemistry/chap-one-atomic-structure/part1AtomAndSubatomicParticles/isotopes.md
                  - 1.1.3 Ions and Deflection in Eletric Field: a-level/h2-chemistry/chap-one-atomic-structure/part1AtomAndSubatomicParticles/chargedParticlesInElectricField.md
                  - 1.1.4 Relative Atomic Masses and Isotopic Abundance: a-level/h2-chemistry/chap-one-atomic-structure/part1AtomAndSubatomicParticles/relativeMasses.md
              - 1.2 Electronic Structure:
                  - 1.2.1 Principal Quantum Shells, Subshells and Orbital: a-level/h2-chemistry/chap-one-atomic-structure/part2ElectronicStructure/quantumShellsAndSubshells.md
                  - 1.2.2 Shapes of Orbitals: a-level/h2-chemistry/chap-one-atomic-structure/part2ElectronicStructure/shapesOfOrbitals.md
                  - 1.2.3 Electronic Configuration of Atoms: a-level/h2-chemistry/chap-one-atomic-structure/part2ElectronicStructure/electronicConfigurationOfAtoms.md
                  - 1.2.4 Electronic Configuration of Ions: a-level/h2-chemistry/chap-one-atomic-structure/part2ElectronicStructure/electronicConfigurationOfIons.md
                  - 1.2.5 Introduction to Transition Elements: a-level/h2-chemistry/chap-one-atomic-structure/part2ElectronicStructure/IntroductionToTransitionElement.md
              - 1.3 Periodicity:
                  - 1.3.1 Number of Quantum Shells and Effective Nuclear Charge: a-level/h2-chemistry/chap-one-atomic-structure/part3Periodicity/quantumShellandEffectiveNuclearCharge.md
                  - 1.3.2 Atomic Radius: a-level/h2-chemistry/chap-one-atomic-structure/part3Periodicity/atomicRadius.md
                  - 1.3.3 Ionic Radius: a-level/h2-chemistry/chap-one-atomic-structure/part3Periodicity/ionicRadius.md
                  - 1.3.4 Ionisation Energy: a-level/h2-chemistry/chap-one-atomic-structure/part3Periodicity/IonisationEnergies.md
      - H2 Physics:
          - 13. Circuit:
              - Learning Outcome: a-level/h2-physics/circuit/learning-outcome.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - path: javascripts/chapOne/s-orbital.js
    type: module
  - path: javascripts/chapOne/p-orbital.js
    type: module
  - path: javascripts/chapOne/d-orbital.js
    type: module
  - path: javascripts/chapOne/orbital-energy-diagram.js
    type: module
  - path: javascripts/chapOne/oxygen-electron-allocation.js
    type: module
  - path: javascripts/chapOne/group-one-atomic-radius.js
    type: module
  - path: javascripts/chapOne/period-two-atomic-radius.js
    type: module
  - path: javascripts/chapOne/group-one-ionic-radius.js
    type: module
  - path: javascripts/chapOne/period-three-ionic-radius.js
    type: module
  - path: javascripts/chapOne/mg-successive-ionisation-energy.js
    type: module
  - path: javascripts/chapOne/group-one-first-ionisation-energy.js
    type: module
  - path: javascripts/chapOne/period-two-first-ionisation-energy.js
    type: module
