site_name: Kin Chong O/A Level Notes
site_url: https://wkc75.github.io/Wong_Kin_Chong_O-A_level_notes/

theme:
  name: material

nav:
  - Home: index.md
  - A Level:
      - H2 Chemistry:
          - 1. Atomic Structure:
              - Learning Outcome: a-level/h2-chemistry/chap-one-atomic-structure/learning-outcome.md
              - 1.1 Atoms and Subatomic Particles: a-level/h2-chemistry/chap-one-atomic-structure/atom-and-subatomic-particles.md
              - 1.2 Isotopes: a-level/h2-chemistry/chap-one-atomic-structure/isotopes.md
              - 1.3 Ions and deflection of charged particles: a-level/h2-chemistry/chap-one-atomic-structure/chargedParticlesInElectricField.md
              - 1.4 Relative Masses: a-level/h2-chemistry/chap-one-atomic-structure/relativeMasses.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
